---
title: "finding tree"
output:
  pdf_document: default
  html_document: default
date: '2023-14-08'
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(ggplot2)
library(tree)
library(dplyr)
library(rpart.plot)
library(randomForest)
library(gridExtra)
library(cowplot)

```

```{r}
responses_syrine <- read.csv("syrine_interpretation_third_run.csv" , colClasses=c(rep('factor', 9)))
responses_syrine
ottley_crouser_final <- read.csv("ottley_crouser_final_cleaned_new_cols.csv")
ottley_crouser_final$UserID=as.factor(ottley_crouser_final$UserID)

joined_raw_syrine <- responses_syrine %>% 
  full_join(ottley_crouser_final)
joined_only_relevant_questions_syrine <- joined_raw_syrine %>% dplyr::select(-c(Q6, Q7,Q8, Q9,Q10, Q16, Q18, Q19, Q20))


```
# question 7
```{r}
q7syrine_data <- joined_only_relevant_questions_syrine%>%
  select(-UserID, -Q10S, -Q16S,-Q18S)
```

q4 just have one answer per id and for 7 only select q7 of my interpretations



```{r}

q7syrine_tree <- rpart(Q7S ~. , data = q7syrine_data, method="class", minsplit=8)
rpart.plot(q7syrine_tree, type = 4, clip.right.labs = FALSE, extra=102)

```
# question 10
```{r}
q10syrine_data <- joined_only_relevant_questions_syrine %>% dplyr::select(-c(1,2,4,5)) 
```

```{r}
q10syrine_tree <- rpart(Q10S ~ . , data = q10syrine_data, method="class",minsplit=8)
rpart.plot(q10syrine_tree, type = 4, clip.right.labs = FALSE, extra=102)

```
clear relevant concise
# question 16
```{r}
q16syrine_data <- joined_only_relevant_questions_syrine %>% dplyr::select(-c(1,2,3,5)) 
```

```{r}
q16syrine_tree <- rpart(Q16S ~ . , data = q16syrine_data, method="class",minsplit=8)
rpart.plot(q16syrine_tree, type = 4, clip.right.labs = FALSE, extra=102)

```
# question 18
```{r}
q18syrine_data <- joined_only_relevant_questions_syrine %>% dplyr::select(-c(1,2,3,4)) 
```

```{r}
q18syrine_tree <- rpart(Q18S ~ . , data = q18syrine_data, method="class", minsplit=8)
rpart.plot(q18syrine_tree, type = 4, clip.right.labs = FALSE, extra=102)

```
# Random Forests Q7
```{r}
# Bag plot q7 for 13 predictor 
q7syrine_data <- na.omit(q7syrine_data)
q7syrine_data$Q7S <- droplevels(q7syrine_data$Q7S, exclude = "")

bag_Q7S_bagged = randomForest(Q7S ~ ., 
                       data = q7syrine_data, 
                       mtry = 13, 
                       importance = TRUE)
plot1 <- varImpPlot(bag_Q7S_bagged)
png("q7_bagged.png")
dev.off()

# Create the second plot and save it as an image
bag_Q7S_randomforest = randomForest(Q7S ~ ., 
                       data = q7syrine_data, 
                       importance = TRUE)
plot2 <- varImpPlot(bag_Q7S_randomforest)
png("q7_randomforest.png")
dev.off()

#png("q7_randomforest.png")
#ggdraw() + 
#  draw_image("q7_bagged.png", width = 0.5) + 
#  draw_image("q7_randomforest.png", width = 0.5, x = 0.5)
```


side by side bagged and randomforest. check if q4 as important as it appears
run each side by side with mtry1 and without. 

# Random Forests Q10
```{r}

q10syrine_data <- na.omit(q10syrine_data)
q10syrine_data$Q10S <- droplevels(q10syrine_data$Q10S, exclude = "")

bag_Q10S_bagged = randomForest(Q10S ~ ., 
                       data = q10syrine_data, 
                       mtry = 13, 
                       importance = TRUE)
varImpPlot(bag_Q10S_bagged)

bag_Q10S_randomforests = randomForest(Q10S ~ ., 
                       data = q10syrine_data, 
                       importance = TRUE)
# Print the model
varImpPlot(bag_Q10S_randomforests)


```
# Random Forests Q16
```{r}

q16syrine_data <- na.omit(q16syrine_data)
q16syrine_data$Q16S <- droplevels(q16syrine_data$Q16S, exclude = "")



bag_Q16S_bagged = randomForest(Q16S ~ ., 
                       data = q16syrine_data, 
                       mtry = 13, 
                       importance = TRUE)
varImpPlot(bag_Q16S_bagged)

bag_Q16S_randomforests = randomForest(Q16S ~ ., 
                       data = q16syrine_data, 
                       importance = TRUE)
# Print the model
varImpPlot(bag_Q16S_randomforests)

```

# Random Forests Q18
```{r}
q18syrine_data <- na.omit(q18syrine_data)
q18syrine_data$Q18S <- droplevels(q18syrine_data$Q18S, exclude = "")

bag_Q18S_bagged = randomForest(Q18S ~ ., 
                       data = q18syrine_data, 
                       mtry = 13, 
                       importance = TRUE)
varImpPlot(bag_Q18S_bagged)

bag_Q18S_randomforests = randomForest(Q18S ~ ., 
                       data = q18syrine_data, 
                       importance = TRUE)
# Print the model
varImpPlot(bag_Q18S_randomforests)


```